# Generated by Django 5.1.1 on 2024-09-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='clients_set', to='client.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_set', to='client.client'),
        ),
    ]
